language: php

php:
  - 5.5
  - 5.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

services: mongodb

before_install:
    - pecl install mongodb
    - echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - composer self-update

install:
    - composer --prefer-source install

notifications:
  email:
    - payumsupport@forma-pro.com
